### ISSUE TITLE
New cortex-m-rt rand dependency breaks builds

### ISSUE THREAD

**Issue by therealprof** [rust-embedded/cortex-m-rt#105]
I was just trying to port the `microbit` crate to `cortex-m-rt` 0.6.0 but I'm facing this here:
```
   Compiling rand_core v0.2.1
   Compiling cortex-m-rt v0.6.0
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv6m-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `rand_core`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

@japaric Seems something is messing (or not) with the required flags for `no_std`.

**Comment by japaric** [comment]
*sigh* this is probably that Cargo limitation where it keeps a single dependency graph for both build-dependencies (compiled for the host) and other dependencies (compiled for the target). Making `rand` not depend on `std` *may* fix this.

**Comment by japaric** [comment]
> Making rand not depend on std may fix this.

I meant our `rand` build dependency not depend on std may fix this.

**Comment by therealprof** [comment]
That works. NB: It's fairly annoying to test that... requires all local checkouts and changing everything to paths because (of course) `cortex-m-rt` is first imported by the peripheral access API crates...

Oh, and I run into another funkiness which prevents me from compiling `cortex-m-rt` examples from the checkout:
```
   Compiling volatile-register v0.2.0
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> macros/src/lib.rs:4:1
  |
4 | extern crate rand;
  | ^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
...
```

**Comment by adamgreig** [comment]
I _don't_ get this error when using the new 0.6.0 on a thumbv7em-none-eabi target. Everything builds fine.

**Comment by japaric** [comment]
@adamgreig this only happens if your crate depend on the `rand` crate.

**Comment by adamgreig** [comment]
Right, I'd just realised but you beat me to pointing it out. Makes sense.

**Comment by therealprof** [comment]
Ah, and I get your point now. Will do. ;)

**Comment by therealprof** [comment]
Can we move this forward?

**Comment by little-arhat** [comment]
What is the plan for this? Will merging https://github.com/therealprof/cortex-m-rt/commit/bddf23b3fa73d2d3abfc7491e352ac106a6111b3 suffice or is there more to it?
