### ISSUE TITLE
Document #[interrupt] in main crate docs

### ISSUE THREAD

**Issue by birkenfeld** [rust-embedded/cortex-m-rt#137]
See e.g. https://docs.rs/cortex-m-rt/0.6.5/cortex_m_rt/: under "Features" it lists `#[entry]`, `#[exception]` and `#[pre_init]` so `#[interrupt]` should probably be listed as well?

**Comment by adamgreig** [comment]
The reason it's not documented is because it's not designed to be used from `cortex_m_rt` itself; it can only be used after being re-exported by a device crate (such as generated by svd2rust) which also exports an `interrupt` enum. Such a crate's docs would then include the `#[interrupt]` docs.

**Comment by birkenfeld** [comment]
Ok - but that might still be good to put into the docs somewhere.

**Comment by adamgreig** [comment]
:+1:
