### ISSUE TITLE
#[cfg(...)] flags don't work

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/cortex-m-rt#178]
The `#[cfg(...)]` flags don't work, which I think is because we don't set them in the build.rs file. I think we need to copy the relevant code from the cortex-m/build.rs file.

This affects armv8m-main because without `#[cfg(armv8)]` you don't get a SecureFault handler.

**Comment by thejpster** [comment]
See https://github.com/rust-embedded/cortex-m-rt/pull/182

**Comment by jonas-schievink** [comment]
It looks like the cfg flag is now set properly:

https://github.com/rust-embedded/cortex-m-rt/blob/7c8778f678d444115d74fd4185f32671b67effdc/build.rs#L53-L55

**Comment by thejpster** [comment]
Yup. Looks like I fixed it already.
