### ISSUE TITLE
.ARM.exidx may need to be ignored in LLD9

### ISSUE THREAD

**Issue by jamesmunns** [rust-embedded/cortex-m-rt#197]
Context in https://github.com/rust-lang/rust/issues/62781.

Testing locally, adding a discard for `*(.ARM.exidx);` will prevent this error, or changing https://github.com/rust-embedded/cortex-m-rt/blob/master/link.x.in#L152 to `*(.ARM.exidx*);` both prevent linker errors. I am not sure which one is more idiomatic.

**Comment by adamgreig** [comment]
I would add `*(.ARM.exidx);` separately to the `.*` one, which is what we do elsewhere in the linker script (e.g. `.got .got.*`) and seems to be more common practice.
