### ISSUE TITLE
Consider backporting LLVM9 support to the 0.5.x release

### ISSUE THREAD

**Issue by jamesmunns** [rust-embedded/cortex-m-rt#200]
https://github.com/rust-embedded/cortex-m-rt/pull/198 fixed an incompatibility with LLVM9 (a new linker section) that looks like it is coming down the pipeline. We should consider making another release in the 0.5.x series to prevent breaking users that use PAC/HALs that have not yet moved to 0.6.x.

**Comment by TeXitoi** [comment]
cortex-m-rt 0.5 use the semver trick, thus such a backport for an hidden internal thing should not be necessary, no?

**Comment by adamgreig** [comment]
Good point. I've just checked and a project depending on cortex-m-rt 0.5 ends up pulling in 0.6.10 now, and the new linker script is the only one that gets used. Convenient!
