### ISSUE TITLE
release cortex-m-rt-macros 0.1.6?

### ISSUE THREAD

**Issue by japaric** [rust-embedded/cortex-m-rt#206]
v0.1.5 is still using pre-1.0 versions of the syn and quote crates. Releasing a new patch version that depends on syn and quote 1.0 would reduce the number of times these crates are built in some Cortex-M applications (e.g. RTFM apps) from twice to once.

Note that is not required to make a release of `cortex-m-rt`; the current version (0.6.10) will automatically pick up the newer patch release of the `-macros` crate thanks to semver.

**Comment by korken89** [comment]
I think yes, I was pushing the other day for cortex-m and cortex-m-rt as well. We are just waiting for a PR with link scripts to land :)
