### ISSUE TITLE
Unable to compile under x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by mamins1376** [rust-embedded/cortex-m-rt#208]
Coming from The Embedded Book, I'm stuck in [the cross-compiling section](https://rust-embedded.github.io/book/start/qemu.html#cross-compiling).

```
# cargo build --target=thumbv6m-none-eabi
error: cannot produce proc-macro for `cortex-m-rt-macros v0.1.5` as the target `thumbv6m-none-eabi` does not support these crate types
```

Also tried to do that with both `RUSTFLAGS='-C target-feature=-crt-static'` and adding that to `.cargo/config`. I think there supposed to be a way to the that specifically to `rustc` when compiling `cortex-m-rt-macros`?

**Comment by thejpster** [comment]
I think this is related to https://github.com/rust-lang/rust/issues/40174.

**Comment by mati865** [comment]
It's not related.
`thumbv6m-none-eabi` doesn't support dynamic linking at all and proc-macros are just shared libraries. I'm not aware of any way to build proc-macros for that target.

**Comment by jonas-schievink** [comment]
The upstream issue has been fixed, closing.
