### ISSUE TITLE
Consider tagging a new release

### ISSUE THREAD

**Issue by lucab** [rust-embedded/cortex-m-rt#220]
First of all, thanks for developing and maintaining this corner-stone crate!

I unfortunately stepped into a mess of conflicting `rand` dependencies/features while playing with some other embedded HAL crates. I traced it down to here, and it looks like current master branch with https://github.com/rust-embedded/cortex-m-rt/pull/205 would solve my headaches.

Can you please tag a new release in the near future? I've heard on Matrix that one should be happening soon™, this ticket is just to avoid it slipping to the side.

**Comment by therealprof** [comment]
Addressed by #221.
