### ISSUE TITLE
v0.6.13 release?

### ISSUE THREAD

**Issue by japaric** [rust-embedded/cortex-m-rt#268]
Did anything breaking land in master since the v0.6.12 release?

I would like to see a v0.6.x release that includes binary-level fixes like #265 (I guess cortex-m had more of that kind of fixes)

**Comment by jonas-schievink** [comment]
This is now released: https://github.com/rust-embedded/cortex-m-rt/blob/v0.6.x/CHANGELOG.md#v0613---2020-09-07
