### ISSUE TITLE
SCB.ICSR is more than 8 bits

### ISSUE THREAD

**Issue by Dirbaio** [rust-embedded/cortex-m-rt#314]
This code here reads ICSR and casts it to 8 bits. In cortex-m3 it is more than 8 bits because there can be up to 480 interrupts. 

https://github.com/rust-embedded/cortex-m-rt/blob/ca4790f40738bcc770285c8080955a2077682078/macros/src/lib.rs#L230

This is the same as https://github.com/rust-embedded/cortex-m/issues/332

**Comment by adamgreig** [comment]
Closed by #315.
