### ISSUE TITLE
Why the code in this repo isn't the same as in crate.io even if the version number is the same?

### ISSUE THREAD

**Issue by Acciente717** [rust-embedded/cortex-m-rt#327]
Just as an example, in this repo, `Reset()` is defined in `asm.S` as assembly code, https://github.com/rust-embedded/cortex-m-rt/blob/master/asm.S

However, in crate.io, `Reset()` is defined in `lib.rs` as Rust code. https://docs.rs/cortex-m-rt/0.6.13/src/cortex_m_rt/lib.rs.html

They all have the version number `0.6.13`. Why is it?

**Comment by adamgreig** [comment]
The code currently in master on this repo will eventually be released as 0.7.0; we update the version number in Cargo.toml just before release (this way it's possible to use cargo patch with the git URL to patch in the latest version). You can view the exact code that's used for each released version on the [Releases page](https://github.com/rust-embedded/cortex-m-rt/releases), e.g. [v0.6.13](https://github.com/rust-embedded/cortex-m-rt/tree/v0.6.13).
