### ISSUE TITLE
master branch is out of date relative to 0.6.14 release

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/cortex-m-rt#328]
This is an issue if you try and patch the git version in for the release version, as the git version appears to be older.

I would open a PR to merge the release branch into master, but I can't find the release branch.

**Comment by adamgreig** [comment]
The release branch is `v0.6.x`, but we don't want to merge it into master as it contains backports since v0.6.12. This should be resolved by the upcoming #329  and #330 though.

**Comment by adamgreig** [comment]
This was closed by #329/#330.
