### ISSUE TITLE
cortex-m-rt doesn't build on Windows anymore

### ISSUE THREAD

**Issue by jcreedon** [rust-embedded/cortex-m-rt#80]
On Windows, with a fresh clean install of `arm-none-eabi-gcc`, building `cortex-m-rt` eventually fails with:

```
Internal error occurred: Failed to find tool. Is `ar` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)
```

As a workaround, setting the `TARGET_AR` environment variable to `arm-none-eabi-ar` fixes it. This was not necessary before, and is not documented anywhere if it is a new requirement.

**Comment by tib888** [comment]
I had the same issue on windows.
Thank you for this fix!

**Comment by japaric** [comment]
IMO, `cc` should be using a prefixed archiver if already using a prefixed compiler / assembler. I have filed alexcrichton/cc-rs#330 to request changing the behavior.

**Comment by jonathanpallant** [comment]
I fell over this today :/
