### ISSUE TITLE
Document the minimum GCC / LD supported version

### ISSUE THREAD

**Issue by japaric** [rust-embedded/cortex-m-rt#89]
As we found out in #84 our linker script is not supported by GCC 4.8 / binutils 2.24. We should document the minimum version that we support.

I know that binutils 2.31 works.

**Comment by mullr** [comment]
2.27, the one currently in ubuntu 18.04, appears not to work. (gives the same error as #92)

**Comment by mvirkkunen** [comment]
Also broken on GCC 6.3.1 which is the current version of gcc-arm-none-eabi in the official Ubuntu repositories. Same error as #92. I switched to LLD for the time being.

**Comment by therealprof** [comment]
@adamgreig Funny you should mention this. I also had various troubles in the past specifically with 2016q3... I would definitely second that we recommend using the latest ARM release, that'll reduce the amount of uncertainty considerably.

**Comment by japaric** [comment]
No longer needed because this crate no longer depends on arm-none-eabi-gcc. :tada:
