### ISSUE TITLE
Document default handlers

### ISSUE THREAD

**Issue by adamgreig** [rust-embedded/cortex-m-rt#93]
After #85 was merged we never updated the documentation to mention the new default handlers. Instead, it still says

> It's mandatory to set the `HardFault` handler somewhere in the dependency graph of an application

which is technically true but a little misleading. We should probably mention the defaults in any event, and possibly update the example in the crate-level documentation to not manually specify the handlers.

**Comment by jonas-schievink** [comment]
Looks like this was done
